"""create meter_readings table

Revision ID: 1c5831fbd52e
Revises: 
Create Date: 2026-03-12 20:11:17.064656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c5831fbd52e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meter_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_id', sa.String(), nullable=True),
    sa.Column('usage_kwh', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meter_readings_id'), 'meter_readings', ['id'], unique=False)
    op.create_index(op.f('ix_meter_readings_meter_id'), 'meter_readings', ['meter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meter_readings_meter_id'), table_name='meter_readings')
    op.drop_index(op.f('ix_meter_readings_id'), table_name='meter_readings')
    op.drop_table('meter_readings')
    # ### end Alembic commands ###
